### ISSUE TITLE
Navigation bar

### ISSUE THREAD

**Issue by fwilson-603** [uoft-lgcu/lgcu.ca#23]
Current problem: the navigation bar at the top is full to the brim, and we can't add any more pages without causing problems.

Three possible solutions:
1. Have the navigation bar wrap around, so that there are 2+ lines.
2. Drop-down menus within the navigation bar.
3. Reducing the links in the navigation bar to a smaller number, some of which link to organizational pages (e.g. a link to 'Stuff' page (or some better title), which contains links to Committees, Events, Books, etc.)

I'm thinking we should sort out how we'd like to *fix* the problem before somebody actually goes and dedicates a bunch of time to actually implementing the fix.

Thoughts?

**Comment by gadanidis** [comment]
It looks like (1) is what happens automatically but it looks quite ugly (e.g., COVID-19 is broken across lines and there's a huge amount of space between the lines). We could probably fix those problems up though. Example (I just duplicated the Books page several times):

![2021-05-12_11:45:08](https://user-images.githubusercontent.com/38380316/118004605-99bf4180-b317-11eb-83e3-b6cef2f5c17f.png)

(3) would be my preference since it's simple and dropdowns can be kind of inaccessible/annoying. But if we want dropdowns we could do a mix of (2) and (3) where the initially-visible part of the dropdown leads to an organizational page, but you can bypass the organizational page using the dropdown.

**Comment by fwilson-603** [comment]
A cleaned-up 1 could work, depending on how many pages we're talking about. I agree with the issue of drop-downs being inaccessible with 2. Transparency might be an issue with 3 (as in, I'm not sure there's a really clear way of grouping pages so that it's 100% obvious where the link someone is look for is going to be, so having to click through fully to figure out that's not where your target is stored could be annoying). If we could get the described mix of 2 and 3 working in a way that's not going to cause havoc for screen readers, that would be my preference.

**Comment by gadanidis** [comment]
I think this is OK for now since I don't think we plan on adding many more pages at this point and we've merged the COVID page with the Health page. But we can come back to this if the site needs to be expanded at some point.
